version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
     - "2181:2181"

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
      - "9092:9092"
    expose:
     - "29092"
    depends_on:
      - zookeeper
    env_file: ./train/modules/broker/config/.env

  con:
    build: ./train/modules/con
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: con
    environment:
      - MODULE_NAME=con
      - MODULE_PORT=6064
    volumes:
      - ./train/shared:/shared
    ports:
      - 6064:6064

  can:
    build: ./train/modules/can
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: can
    environment:
      - MODULE_NAME=can
      - MODULE_PORT=6065
    volumes:
      - ./train/shared:/shared
    ports:
      - 6065:6065

  iy:
    build: ./train/modules/iy
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: iy
    environment:
      - MODULE_NAME=iy
      - MODULE_PORT=6066
    volumes:
      - ./train/shared:/shared
    ports:
      - 6066:6066

  saytp:
    build: ./train/modules/saytp
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: saytp
    environment:
      - MODULE_NAME=saytp
      - MODULE_PORT=6067
    volumes:
      - ./train/shared:/shared
    ports:
      - 6067:6067

  rpdp:
    build: ./train/modules/rpdp
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: rpdp
    environment:
      - MODULE_NAME=rpdp
      - MODULE_PORT=6068
    volumes:
      - ./train/shared:/shared
    ports:
      - 6068:6068

  oskp:
    build: ./train/modules/oskp
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: oskp
    environment:
      - MODULE_NAME=oskp
      - MODULE_PORT=6069
    volumes:
      - ./train/shared:/shared
    ports:
      - 6069:6069

  pir:
    build: ./train/modules/pir
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: pir
    environment:
      - MODULE_NAME=pir
      - MODULE_PORT=6070
    volumes:
      - ./train/shared:/shared
    ports:
      - 6070:6070

  pri:
    build: ./train/modules/pri
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: pri
    environment:
      - MODULE_NAME=pri
      - MODULE_PORT=6071
    volumes:
      - ./train/shared:/shared
    ports:
      - 6071:6071

  tskbm:
    build: ./train/modules/tskbm
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: tskbm
    environment:
      - MODULE_NAME=tskbm
      - MODULE_PORT=6072
    volumes:
      - ./train/shared:/shared
    ports:
      - 6072:6072

  bi:
    build: ./train/modules/bi
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: bi
    environment:
      - MODULE_NAME=bi
      - MODULE_PORT=6073
    volumes:
      - ./train/shared:/shared
    ports:
      - 6073:6073

  disp:
    build: ./train/modules/disp
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: disp
    environment:
      - MODULE_NAME=disp
    ports:
      - "6074:6074"

  scb:
    build: ./train/modules/scb
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: scb
    environment:
      - MODULE_NAME=scb
      - MODULE_PORT=6075
    volumes:
      - ./train/shared:/shared
    ports:
      - 6075:6075

  trust-can:
    build: ./train/modules/trustCan
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: trust-can
    environment:
      - MODULE_NAME=trust-can
      - MODULE_PORT=6076
    volumes:
      - ./train/shared:/shared
    ports:
      - 6076:6076

  bvi:
    build: ./train/modules/bvi
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: bvi
    environment:
      - MODULE_NAME=bvi
      - MODULE_PORT=6077
    volumes:
      - ./train/shared:/shared
    ports:
      - 6077:6077

  chipher:
    build: ./train/modules/chipher
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: chipher
    environment:
      - MODULE_NAME=chipher
      - MODULE_PORT=6078
    volumes:
      - ./train/shared:/shared
    ports:
      - 6078:6078

  monitor:
    build: ./train/modules/monitor
    entrypoint:
      - bash
      - -c
      - |
        echo 'Giving Kafka a bit of time to start up…'
        sleep 20
        venv/bin/python start.py /shared/config.ini
    container_name: monitor
    environment:
      - MODULE_NAME=monitor
    volumes:
      - ./train/shared:/shared
